# Generated by Django 4.2.7 on 2023-11-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(upload_to='')),
                ('item_name', models.TextField(max_length=100)),
                ('item_value', models.IntegerField(null=True)),
            ],
        ),
    ]
