# Generated by Django 4.2.7 on 2023-11-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoporder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='')),
                ('product_name', models.TextField(max_length=50)),
                ('product_qty', models.IntegerField()),
                ('product_amount', models.IntegerField()),
                ('ship_address', models.TextField(max_length=100)),
                ('ship_mobile', models.IntegerField(null=True)),
                ('payment', models.TextField(max_length=30)),
            ],
        ),
    ]
