# Generated by Django 4.2.7 on 2023-11-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_shoporder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shopitems',
        ),
        migrations.DeleteModel(
            name='shoporder',
        ),
    ]
