# Generated by Django 4.2.7 on 2023-11-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0003_delete_shopitems_delete_shoporder'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='')),
                ('product_name', models.TextField(max_length=20)),
                ('product_value', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'product_items',
            },
        ),
    ]
