# Generated by Django 4.2.7 on 2023-12-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_userimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='userimage',
            new_name='userpic',
        ),
    ]
