# Generated by Django 4.2.7 on 2023-12-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_userimage_userimage_userpic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_items',
            new_name='collection',
        ),
        migrations.AlterModelTable(
            name='collection',
            table=None,
        ),
    ]
