# Generated by Django 4.2.7 on 2023-12-15 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rename_product_items_collection_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collection',
            table='collection',
        ),
    ]
