# Generated by Django 4.2.7 on 2023-12-15 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_collection_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_order',
            name='product_items_class',
        ),
        migrations.DeleteModel(
            name='collection',
        ),
        migrations.DeleteModel(
            name='product_order',
        ),
    ]
