# Generated by Django 4.2.7 on 2023-12-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_items_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_detail',
            name='trending',
            field=models.BooleanField(null=True),
        ),
    ]
