# Generated by Django 4.2.7 on 2023-12-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_mobiledetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledetails',
            name='storage',
            field=models.IntegerField(),
        ),
    ]
