# Generated by Django 4.2.7 on 2023-12-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_mobiledetails_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledetails',
            name='stack',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mobiledetails',
            name='storage',
            field=models.CharField(max_length=50),
        ),
    ]
