# Generated by Django 4.2.7 on 2023-12-29 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_items_detail_prize_items_detail_stack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobiledetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(max_length=50)),
                ('rear_camera', models.CharField(max_length=100)),
                ('fornd_camera', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=100)),
                ('mobile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.items_detail')),
            ],
        ),
    ]
